name = "prompt-hub"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "prompt-hub"

[[d1_databases]]
binding = "DB"
database_name = "prompt_hub"
database_id = "9efe31be-b125-4fe9-9616-339aa48596f4"
preview_database_id = "9efe31be-b125-4fe9-9616-339aa48596f4"
migrations_dir = "migrations"
